-- SQL Schema for WhatsApp Calorie Tracker

-- 1. Create the Users table
CREATE TABLE public.users (
    phone text primary key,
    daily_goal_kcal integer default 2000,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create the Meals table
CREATE TABLE public.meals (
    id bigint generated by default as identity primary key,
    phone text references public.users(phone) ON DELETE CASCADE not null,
    dish text not null,
    kcal integer not null,
    protein_g numeric default 0,
    carbs_g numeric default 0,
    fat_g numeric default 0,
    logged_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Security (Row Level Security)
-- This blocks public anonymous requests from the internet
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meals ENABLE ROW LEVEL SECURITY;

-- Note: Because your backend uses the Supabase Service Role Key / environment variables, 
-- your Node app will bypass these RLS policies automatically. No complex policy setup required!
